# .travis.yml

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

script:
  - docker build --pull -t nixos/nix ./alpine
  - docker run -it --rm nixos/nix nix-channel --list
  - docker run -it --rm nixos/nix sh -l -c 'nix-env -iA nixpkgs.hello && test "$(hello)" = "Hello, world!"'
